name:                optimization-algorithms
version:             0.1.0.0
github:              mizunno/optimization-algorithms
license:             BSD3
author:              Pedro García Victoria
maintainer:          pedrogarciavictoria@gmail.com
copyright:           2018 Pedro García Victoria

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Nature-inspired algorithms
# category:            Artificial Intelligence

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mizunno/optimization-algorithms#readme>

dependencies:
- base >= 4.7 && < 5
- random
- mtl

library:
  source-dirs: src

executables:
  optimization-algorithms-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optimization-algorithms

tests:
  optimization-algorithms-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optimization-algorithms
